# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-31 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0002_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachments',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
