# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-02 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0004_auto_20171230_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biography',
            options={'verbose_name_plural': 'biographies'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published',)},
        ),
    ]
