# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-25 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('houses', '0001_initial'), ('houses', '0002_auto_20171005_2354'), ('houses', '0003_fraternity_motto')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fraternity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=30)),
                ('nickname', models.CharField(blank=True, max_length=30)),
                ('letters', models.ImageField(upload_to='letters')),
                ('primary_color', models.CharField(max_length=7)),
                ('secondary_color', models.CharField(max_length=7)),
                ('featured_picture', models.ImageField(blank=True, upload_to='featured')),
                ('values', models.TextField(blank=True)),
                ('extra_info', models.TextField(blank=True)),
                ('house_pic', models.ImageField(blank=True, upload_to='house')),
                ('motto', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'fraternities',
            },
        ),
    ]
