# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fraternity',
            old_name='pimary_color',
            new_name='primary_color',
        ),
    ]
