# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-25 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_squashed_0003_fraternity_motto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraternity',
            name='letters',
            field=models.ImageField(blank=True, upload_to='letters'),
        ),
    ]
