# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-11 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20180524_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraternity',
            name='calendar_link',
            field=models.URLField(blank=True),
        ),
    ]
